In [1]:
import numpy as np
import pylab
import time
from pathlib import Path

from PyBoltz.PyBoltzRun import *

In [2]:
# Set up helper object
PBRun=PyBoltzRun()

In [3]:
# Show list of available gases
PBRun.ListGases()

CF4 1
ARGON 2
HELIUM4 3
HELIUM3 4
NEON 5
KRYPTON 6
XENON 7
CH4 8
ETHANE 9
PROPANE 10
ISOBUTANE 11
CO2 12
H2O 14
OXYGEN 15
NITROGEN 16
HYDROGEN 21
DEUTERIUM 22
DME 25


In [4]:
# Configure settings for our simulation
MySettings   ={'Gases'                 :['XENON'],
               'Fractions'             :[100],
               'Max_collisions'        :4e8,
               'EField_Vcm'            :500,
               'Max_electron_energy'   :0,
               'Temperature_C'         :23,
               'Pressure_Torr'         :7500.62,
               'BField_Tesla'          :0,
               'BField_angle'          :0,
               'Angular_dist_model'    :1,
               'Enable_penning'        :0,
               'Enable_thermal_motion' :1,
               'ConsoleOutputFlag'     :0}

In [5]:
# Create empty lists to store outputs
DriftVels=[]
DriftVels_err=[]
DTs=[]
DLs=[]
DT1s=[]
DL1s=[]
DTs_err=[]
DLs_err=[]
DT1s_err=[]
DL1s_err=[]

In [6]:

# Run for each E field

#EFields=[436.7,476.2,20000]
EFields=[438,476,500]
t1=time.time()
for E in EFields:
    print("Running with E Field " +str(E))

    MySettings['EField_Vcm']=E
    
    Output=PBRun.Run(MySettings)

    DriftVels.append(Output['Drift_vel'].val[2])
    DriftVels_err.append(Output['Drift_vel'].err[2])

    DTs.append(Output['DT'].val)
    DTs_err.append(Output['DT'].err)
    
    DLs.append(Output['DL'].val)
    DLs_err.append(Output['DL'].err)
    
    DT1s.append(Output['DT1'].val)
    DT1s_err.append(Output['DT1'].err)

    DL1s.append(Output['DL1'].val)
    DL1s_err.append(Output['DL1'].err)
t2=time.time()

print("Time elapsed:" +str(t2-t1))

Running with E Field 438
Input Decor_Colls not set, using default 0
Input Decor_LookBacks not set, using default 0
Input Decor_Step not set, using default 0
Input NumSamples not set, using default 10

Running with E Field 476

Running with E Field 500

Time elapsed:1380.4733214378357


In [7]:
# Lets look a what output info we have
print(Output.keys())

dict_keys(['Drift_vel', 'DT', 'DL', 'DT1', 'DL1', 'MeanEnergy', 'DTensor', 'ReducedIonization', 'ReducedAttachment', 'AlphaSST'])


In [8]:
print("\n TDiffusion cm^2/s^2\n")
print(DTs)
print("\n DTs error ")
print(DTs_err)
print("\n LDiffusion cm^2/s^2\n")
print(DLs)
print("Error")
print(DLs_err)
print("\nDrift Velocity mm/us\n")
print(DriftVels)
print("Error")
print(DriftVels_err)
print("\nTDiffusion mm*sqrt(cm)\n")
DT=np.array(DT1s)/1000
DT_err=np.array(DT1s_err)/1000

print("Transverse Diffusion")
print(DT)

print("Error")
print(DT_err)
print("\nLDiffusion mm*sqrt(cm)\n")

print ("Long Diffusion")
DL=np.array(DL1s)/1000
DL_err=np.array(DL1s_err)/1000
print("DL")
print(DL)
print("DL_err")
print(DL_err)



 TDiffusion cm^2/s^2

[383.9905670910257, 395.7970043845769, 381.38315221822734]

 DTs error 
[13.157461760230598, 16.287789349001667, 12.939819145788926]

 LDiffusion cm^2/s^2

[66.262017755919, 61.15029422787139, 60.29072975701495]
Error
[1.8266044039730105, 1.434434719431793, 1.3224135369669128]

Drift Velocity mm/us

[0.9499443921712526, 0.9459665724227121, 0.9801242487113394]
Error
[0.01070075500573733, 0.009620623723793015, 0.010164616065732825]

TDiffusion mm*sqrt(cm)

Transverse Diffusion
[0.89913765 0.91477303 0.88217589]
Error
[0.01621558 0.0193886  0.01564903]

LDiffusion mm*sqrt(cm)

Long Diffusion
DL
[0.37350656 0.35956415 0.35075163]
DL_err
[0.00556135 0.00459654 0.00425499]
